---
title: "Post-cop trait on paternity"
author: "Erin Macartney"
date: '2023-01-10'
output: html_document
---
# Setting up {.tabset}

## Loading packages
```{r, message = FALSE}
pacman::p_load(tidyverse, 
               here, 
               metafor, 
               clubSandwich, 
               orchaRd,
               rotl,
               ape,
               phytools,
               ggtree,
               ggtreeExtra)
```

## Loading data and functions
```{r, message = FALSE}
# dat <- read_csv(here("Data", "Data_raw.csv")) #raw data was used for data processing below

dat <- read_csv(here("Data", "processed_data.csv"))
source(here("R/func.R")) #functions for converting other statistics into correlations
tree <- read.tree(file = "species_tree.tre") #loading phylogenetic tree
```

## Calculating r
```{r, eval = FALSE}
effect_size_group2 <- with(dat, mapply(group2, 
                                       mean_low, mean_high, 
                                       SD_low, SD_high, 
                                       n_low, n_high))


#only selecting study that reported mean of for groups

# dat_a <- dat %>%
#   filter(First_author == "Yamane")

# effect_size_group4 <- with(dat_a, mapply(group4, 
#                                        mean_low, mean_med1, mean_med2, mean_high,
#                                        SD_low, SD_med1, SD_med2, SD_high,
#                                        n_low, n_med1, n_med2, n_high,
#                                        sim = 100000))

#manually added these correlations based on the function above


effect_size_est <- with(dat, mapply(est_se_b, estimate,SE, N))

effect_size_t <- with(dat, mapply(t_vals_b, t, N))

effect_size_F <- with(dat, mapply(F_vals_b, F, N, reverse = FALSE))

effect_size_p <- with(dat, mapply(p_vals_b, p, N, reverse = FALSE))


dat2 <- bind_cols(dat, "effect_size_group2" = effect_size_group2, "effect_size_est" =  effect_size_est, "effect_size_t" =  effect_size_t, "effect_size_F" = effect_size_F, "effect_size_p" = effect_size_p)

#removing unclear F stat direction
df2 <- subset(dat2, Effectsize_ID !='3')

#combining all r into one column

df3 <- df2 %>%
    select("Effectsize_ID","Corr_r", "effect_size_group2", "effect_size_est","effect_size_t", "effect_size_F", "effect_size_p")%>% pivot_longer(cols = -Effectsize_ID, values_to = "effect_size", names_to = "summary_statistic") %>% drop_na() 

#merging back with df2

df4 <- merge(df3, df2, by = "Effectsize_ID")

# df2 %>% pivot_longer(cols = c("Corr_r", "effect_size_group2", "effect_size_est","effect_size_t", "effect_size_F", "effect_size_p"), values_to = "effect_size", names_to = "summary_statistic") %>% drop_na(effect_size)

#flipping effect size so that higher = better
df4$effect_size2<- ifelse(df4$Coin == 2, -df4$effect_size, df4$effect_size) 

# write.csv(df4, "processed_data.csv")

```

## Making species tree

```{r, eval = FALSE}

length(unique(df4$Species)) #34 species
unique(df4$Species)

taxa <- tnrs_match_names(unique(df4$Species))
table(taxa$approximate_match) #34

# mytree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format= "name")
#HTTP failure: 400 [/v3/tree_of_life/induced_subtree] Error: node_id 'ott3411771' was not found!list(ott3411771 = "pruned_ott_id")

taxa[taxa[["ott_id"]] == "3411771", ] #gryllus_bimaculatus 
df4$Species[df4$Species == "Gryllus_bimaculatus"]  <- "Gryllus_bimaculata"
df4$Species[df4$Species == "Xiphophorus_helleri"]  <- "Xiphophorus_hellerii"

taxa <- tnrs_match_names(unique(df4$Species))

mytree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format= "name") # comes up with warning about dropping singleton nodes

sort(setdiff(unique(df4$Species), as.character(mytree$tip.label))) #"Drosophila_melanogaster" "Gadus_morhua"            "Gryllus_bimaculata"      "Sus_domestica" "Coregonus_lavaretus"  "Cyprinus_carpio"  names not matching
#allocating drosophila melanogaster to wrong ottID
#changing names of other species

# plot(mytree, show.tip.label = T, cex = 0.8, no.margin = TRUE)

#allocating correct OTTID
inspect(taxa, taxon_name = "Drosophila_melanogaster")
taxa <- update(taxa, taxon_name = "Drosophila_melanogaster", new_row_number = 1)

inspect(taxa, taxon_name = "Cyprinus_carpio")
taxa <- update(taxa, taxon_name = "Cyprinus_carpio", new_row_number = 1)

inspect(taxa, taxon_name = "Coregonus_lavaretus")
taxa <- update(taxa, taxon_name = "Coregonus_lavaretus", new_row_number = 1)

mytree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format= "name")

df4$Species[df4$Species == "Gryllus_bimaculata"]  <- "Gryllus_bimaculatus"
# mytree <- tol_induced_subtree(ott_ids = taxa$ott_id, label_format= "name")

# changing tip labels
mytree$tip.label[mytree$tip.label == "Sus_scrofa_domesticus"]  <- "Sus_domestica"
mytree$tip.label[mytree$tip.label == "Gadus_morhua_(species_in_domain_Eukaryota)"]  <- "Gadus_morhua"

sort(setdiff(unique(df4$Species), as.character(mytree$tip.label))) # all names match

plot(mytree, show.tip.label = T, cex = 0.8, no.margin = TRUE)
str(mytree)

write.tree(mytree, file = "species_tree.tre")
```

## Calculating Zr and Variance

```{r, eval = FALSE}
zr <- escalc(measure = "ZCOR", ni = df4$N, ri = df4$effect_size2)

#adding back to dataframe 

df5 <- bind_cols(df4, zr)

write.csv(df5, "processed_data.csv")

```


# Data exploration

```{r}
#number of effect sizes

length(unique(dat$Effectsize_ID)) #note that effect_size2 has the effect size flipped so that higher = better
#why does data go down to 106 then?

#number of studies

length(unique(dat$Study_ID))

# Publication year range

min(dat$Year_published)
max(dat$Year_published)

#number of species
length(unique(dat$Species))

#number of classes
length(unique(dat$Class))

#number of classes
dat %>%
  group_by(Class) %>%
  summarise(n = n_distinct(Study_ID))

#traits
dat %>%
  group_by(PC_type) %>%
  summarise(n = n_distinct(Effectsize_ID))

# Cause of PC variation 

dat %>%
  group_by(PC_variation_cause) %>%
  summarise(n = n_distinct(Effectsize_ID))

# rearing type

dat %>%
  group_by(Rearing_type) %>%
  summarise(n = n_distinct(Study_ID))
```

## Figure of species and class

```{r}
sample_data <- count(dat, Species)
sample_data <- as.data.frame(sample_data)
sample_data2 <- mutate(sample_data, tip.label = Species)

tree$tip.label <- strip_ott_ids(tree$tip.label, remove_underscores = TRUE)

sample_data3 <- left_join(sample_data2, dat[, c("Species", "Class")],
    by = "Species")

sample_data4 <- distinct(sample_data3, Species, .keep_all = TRUE)

sample_data4$Species <- as.factor(sample_data4$Species)
sample_data4$tip.label <- as.factor(sample_data4$tip.label)
sample_data4$Class <- as.factor(sample_data4$Class)

cols <- c("yellow", "violet", "turquoise", "tomato", "thistle", "springgreen", "navy")

#TODO need to add classes etc to figure
tree2 <- ggtree(tree, layout = "circular")
```

# Analysis {.tabset}

## Global effect size

```{r}

dat$Species[dat$Species == "Gryllus_bimaculata"]  <- "Gryllus_bimaculatus"
```

```{r}
branchlength<- compute.brlen(tree, method="Grafen", power=1)
VCV_species <- vcv(branchlength, corr=TRUE)


m0 <- rma.mv(yi = yi, V = vi, random = list(~1|Study_ID,
                                            ~1|Effectsize_ID,
                                            ~1|Species),
             R=list(Species = VCV_species),
             data = dat)

summary(m0)

i2_ml(m0)

#TODO how do I get pagel lambda / how much variation is explained due to phylogeny?

```

```{r}
orchard_plot(m0, mod = "1", xlab = "zr", alpha=0.4, group = "Study_ID", data = dat) 
 
```

## Meta-regression {.tabset}

### Traits

```{r}

dat$PC_type<-as.factor(dat$PC_type)

#TODO need to remove trait 2 (testes size)

m1 <- rma.mv(yi = yi, V = vi, mod = ~PC_type-1,  random = list(~1|Study_ID,                        ~1|Effectsize_ID, ~1|Species),
             R=list(Species = VCV_species),
             test = "t",
             data = dat)


summary(m1)

r2_ml(m1)


fig.2 <- orchard_plot(m1, mod = "PC_type", group = "Study_ID", data = dat, xlab = "zr", alpha=0.4) 

```

### Trait variation cause

```{r}

dat$PC_variation_cause<-as.factor(dat$PC_variation_cause)

m2 <- rma.mv(yi = yi, V = vi, mod = ~PC_variation_cause-1,  random = list(~1|Study_ID,                        ~1|Effectsize_ID, ~1|Species),
             R=list(Species = VCV_species),
             test = "t",
             data = dat)

summary(m2)

r2_ml(m2)


fig.3 <- orchard_plot(m2, mod = "PC_variation_cause", group = "Study_ID", data = dat, xlab = "zr", alpha=0.4) 

fig.3

```

### Lab vs Wild-caught

```{r}

dat$Rearing_type<-as.factor(dat$Rearing_type)

#TODO need to remove 3 (agriculture)

m3 <- rma.mv(yi = yi, V = vi, mod = ~Rearing_type-1,  random = list(~1|Study_ID,                        ~1|Effectsize_ID, ~1|Species),
             R=list(Species = VCV_species),
             test = "t",
             data = dat)

summary(m3)

r2_ml(m3)


fig.4 <- orchard_plot(m3, mod = "Rearing_type", group = "Study_ID", data = dat, xlab = "zr", alpha=0.4) 

fig.4

```

### Internal vs external fertilisation

```{r}

dat$Fertilisation_mode<-as.factor(dat$Fertilisation_mode)

m4 <- rma.mv(yi = yi, V = vi, mod = ~Fertilisation_mode-1,  random = list(~1|Study_ID,                        ~1|Effectsize_ID, ~1|Species),
             R=list(Species = VCV_species),
             test = "t",
             data = dat)

summary(m4)

r2_ml(m4)


fig.5 <- orchard_plot(m4, mod = "Fertilisation_mode", group = "Study_ID", data = dat, xlab = "zr", alpha=0.4) 

fig.5 #no difference between fertilisation mode but 
#TODO lets looks at subanalysis. Perhaps different traits are doing different things

```

### Precedence 

```{r}
#TODO need to think about this category some more
#TODO could also do subanalysis
#TODO Not sure how to deal with this category. Might be too hard

dat$Precendence<-as.factor(dat$Precendence)

m5 <- rma.mv(yi = yi, V = vi, mod = ~Precendence-1,  random = list(~1|Study_ID,                        ~1|Effectsize_ID, ~1|Species),
             R=list(Species = VCV_species),
             test = "t",
             data = dat)

summary(m5)

r2_ml(m5)


fig.6 <- orchard_plot(m5, mod = "Precendence", group = "Study_ID", data = dat, xlab = "zr", alpha=0.4) 

fig.6
```

### Competition order 

```{r}
#TODO a sub analysis for this might make more sense and test for differences in traits and phylo signal

dat$Competition_order<-as.factor(dat$Competition_order)

m6 <- rma.mv(yi = yi, V = vi, mod = ~Competition_order-1,  random = list(~1|Study_ID,                        ~1|Effectsize_ID, ~1|Species),
             R=list(Species = VCV_species),
             test = "t",
             data = dat)

summary(m6)

r2_ml(m6)


fig.7 <- orchard_plot(m6, mod = "Competition_order", group = "Study_ID", data = dat, xlab = "zr", alpha=0.4) 

fig.7
```


